language: node_js
deploy:
  provider: npm
  email: jesse.luoto@gmail.com
  api_key:
    secure: dC9Y3rqHuC7qKtNJsLW1EffXvXnE/ChI5iHctvCJM1Eo02aoxA1Idv/bkRz+kcrOBEFdkd5irUDvEHiLc/3YfJ2v3l8jIVVdV3oNXRA9ilUhWfXBA0xW5UrTWjO13LmZHpM42NkjlXq0gCvR+qrTxmry+D/zQBR/s5HQzk6XOxbPLCdZxl/ECz7yYD1S3rlpsnJ1AofKgJBOALHYDinqBbXft8pdBeBUTM/CxV/l8CSYRxlt2oMUQdr18cyAh9/YtcGKjWvijbTl4pxSVFtvGpYPszXipf4t6wM0lhDVzcIM/PxebkoTvdPutCPDOzkgOnW0j9asixiSplpsEZkXm5ZUKIMqHXgf8mNb9WCSyWG2AOGZOmLwuXAuI+GmThu3rX07vlDfODSqL2Cv6ie5W+i7MU/Nvyow4828b7bofliG1DwdINptY1PhIUoOuRgbd3QYV0YXCofXPClnaf9AvoZejkrJWxV+JQJWe+s6pri6cSqPm1MSHRwL5uoeClU+fWvnl/3rjmLSgK76PzxIjuVJMozhSFGF6SiJNcTOAe6bPT5j9n63llBlulEBkqAnDNrKdkr7e4I7uSqJ3tEVzm/uvx6miXJF5+mT/N/pY9hgSKxlIvLGfxPQ+k5/qnQTPjKpzUB0UcvQyIBxDItfaZWYVs6JiwCSFK3T6gkwRjE=
  on:
    tags: true
    repo: jehna/longwood-usestate
  skip_cleanup: 'true'
before_script:
- yarn test && yarn build
